### ISSUE TITLE
Needed Help in Configuring Clover for Asus VivoBook S14 S430 FA

### ISSUE THREAD

**Issue by pavankumar-go** [kadalcj/Hackintosh_Catalina_Asus_VivoBook_S14_S430FN#1]
Hi, 
I'm new to installing hackintosh. i own a similar Asus Model "S14 S430-FA". can you please help me with configuring clover configurations required.

**Comment by kadalcj** [comment]
You can pull my repository and put it on you EFI Partition so you can boot using my configuration

**Comment by pavankumar-go** [comment]
Yeah i did the same, but during catalina installation I get this error : "an error occurred while preparing the installation", near the end of the initial install of Catalina, at about 2 min remaining.
<img width="446" alt="Screenshot 2020-07-26 at 8 53 57 AM" src="https://user-images.githubusercontent.com/64532630/88470720-93dda880-cf1d-11ea-90ba-4a2ad87ae933.png">
Did you install it on SSD or HDD?
i got the above error when i tried to install in on HDD, "unable to setup bless on disk"

**Comment by kadalcj** [comment]
I install it on SSD.

Did you use prebuild image or build your self? If you use prebuild image I suggest you to use the included config and use my config when Hackintosh already successfully installed

**Comment by pavankumar-go** [comment]
can you provide the download link for the prebuild image you used? i used the one from app store and using command line i created the install media and then i replaced the clover with yours clover folder

**Comment by pavankumar-go** [comment]
hey bro, its working now

**Comment by kadalcj** [comment]
Cool. Let me know if you need anything

**Comment by pavankumar-go** [comment]
So everything installed successfully but if i remove the usb-installation media to boot from SSD, its not showing up as a boot option in BIOS, everytime after starting it takes me to BIOS and i don't see the catalina hackintosh boot option. i need to insert the USB that i used to choose to Boot from :(
have you encountered this issue?

**Comment by kadalcj** [comment]
Try to install clover bootloader, after that replace with my config

**Comment by pavankumar-go** [comment]
you mean install the whole macos again?

**Comment by kadalcj** [comment]
No, I mean just install the bootloader. Just download and install the clover bootloader on the Mac

**Comment by pavankumar-go** [comment]
okay will do

**Comment by pavankumar-go** [comment]
okay EFI partition where macos was installed didn't have any folder in it, i copied over your EFI partition. i can boot without USB now, thanks. But did you find a fix for wifi not working in your laptop?

**Comment by kadalcj** [comment]
Intel WiFi is not supported by Mac.

But, there was a way to enabled it. I've tried it, but I not recommend it for now.

**Comment by pavankumar-go** [comment]
okay cool, i'll let you know if i find any
anyway thanks for sharing your clover EFI. looking for it since 2 weeks. keep up the good work

**Comment by kadalcj** [comment]
Thanks :D

**Comment by tareqmahmud** [comment]
> hey bro, its working now

Sorry for opening this issue again.

@pavankumar-go Could you please tell me how did you solve that issue?

**Comment by kadalcj** [comment]
> > hey bro, its working now
> 
> Sorry for opening this issue again.
> 
> @pavankumar-go Could you please tell me how did you solve that issue?

What you need bro?

**Comment by tareqmahmud** [comment]
I'm also facing "an error occurred while preparing the installation," near the end of Catalina's initial install. I saw @pavankumar-go somehow solved that issue.

Just another query after Hackintosh, did you succeed in using Bluetooth?

**Comment by kadalcj** [comment]
About that, I can't say for sure. We need @pavankumar-go to answer it.

And about Bluetooth, I think it works out of the box. But you can't turn it off

**Comment by pavankumar-go** [comment]
Hi @tareqmahmud, i got the 'an error occurred while preparing the installation' because i had formatted the drive as `APFS`, after reformatting it to `MAC OS Extended`its worked fine

**Comment by pavankumar-go** [comment]
And @kadalcj how did you enable wifi and bluetooth, only usb tethering works. can you give us the steps that you used. its okay if its hacky, without wifi its pretty much useless for me to use hackintosh

**Comment by tareqmahmud** [comment]
> Hi @tareqmahmud, i got the 'an error occurred while preparing the installation' because i had formatted the drive as `APFS`, after reformatting it to `MAC OS Extended`its worked fine

Thanks bro. I just installed the os but Bluetooth isn't working out of the box. for wifi you can try this, https://github.com/OpenIntelWireless/itlwm

I'm not sure itlwm will work or not, but some s430 user was successfully got wifi with itlwm.

**Comment by tareqmahmud** [comment]
> About that, I can't say for sure. We need @pavankumar-go to answer it.
> 
> And about Bluetooth, I think it works out of the box. But you can't turn it off

Thanks for your answer bro.

**Comment by pavankumar-go** [comment]
@tareqmahmud  I was about to upload my EFI for you to see if that works

**Comment by pavankumar-go** [comment]
> > Hi @tareqmahmud, i got the 'an error occurred while preparing the installation' because i had formatted the drive as `APFS`, after reformatting it to `MAC OS Extended`its worked fine
> 
> Thanks bro. I just installed the os but Bluetooth isn't working out of the box. for wifi you can try this, https://github.com/OpenIntelWireless/itlwm
> 
> I'm not sure itlwm will work or not, but some s430 user was successfully got wifi with itlwm.

did it work for you?

**Comment by kadalcj** [comment]
> And @kadalcj how did you enable wifi and bluetooth, only usb tethering works. can you give us the steps that you used. its okay if its hacky, without wifi its pretty much useless for me to use hackintosh

You can follow [this](https://www.youtube.com/watch?v=ICpgYtzbxP8) video

**Don't install it on your SLE, just load it using terminal whenever you log in into the Hackintosh**

**Comment by pavankumar-go** [comment]
i tried this before, it didn't work :( , i need to replace my wifi module with one that hackintosh supports

**Comment by kadalcj** [comment]
> > Hi @tareqmahmud, i got the 'an error occurred while preparing the installation' because i had formatted the drive as `APFS`, after reformatting it to `MAC OS Extended`its worked fine
> 
> Thanks bro. I just installed the os but Bluetooth isn't working out of the box. for wifi you can try this, https://github.com/OpenIntelWireless/itlwm
> 
> I'm not sure itlwm will work or not, but some s430 user was successfully got wifi with itlwm.

I can't remember if I was doing something to make the bluetooth work. But it was working just like normal

**Comment by kadalcj** [comment]
> i tried this before, it didn't work :( , i need to replace my wifi module with one that hackintosh supports

Is that so? I've tried it and it work. But the performance is not as good as when I was on Linux
I was trying on this Laptop and my Main Laptop, the MSI GP62 6QF. It works, but I still choose wifi adapter

**Comment by pavankumar-go** [comment]
my wifi-card is `2295f` is your card is of same model number?
<img width="471" alt="Screenshot 2020-08-24 at 11 43 46 AM" src="https://user-images.githubusercontent.com/64532630/91009854-1336c880-e5ff-11ea-8a8b-fee252cd4916.png">

**Comment by tareqmahmud** [comment]
@pavankumar-go I research about that wifi issue for the last two days, and it looks like S430-FA use Realtek rtl8822be for wifi and bluetooth, which isn't supported by Hackintosh yet.

I've to replace the card which will be supported by kext.

**Comment by tareqmahmud** [comment]
@pavankumar-go another query, what's the status of the battery drain? It looks like this model for Hackintosh drain battery too fast.

**Comment by kadalcj** [comment]
> my wifi-card is `2295f` is your card is of same model number?
> <img alt="Screenshot 2020-08-24 at 11 43 46 AM" width="471" src="https://user-images.githubusercontent.com/64532630/91009854-1336c880-e5ff-11ea-8a8b-fee252cd4916.png">

I'm not sure about the model number

**Comment by kadalcj** [comment]
> @pavankumar-go another query, what's the status of the battery drain? It looks like this model for Hackintosh drain battery too fast.

It drain battery fast because of the discrete graphic (Nvidia) still taking power even if we already disable it

**Comment by tareqmahmud** [comment]
Maybe this is the case for the s430-fn version. For s430-fa doesn't have discrete GPU.

**Comment by kadalcj** [comment]
Oh, I didn't know about that. If that so, maybe there was slightly different configuration about the hardware choice so that make you need to tinkering my config to suit with your Laptop version

**Comment by pavankumar-go** [comment]
> @pavankumar-go another query, what's the status of the battery drain? It looks like this model for Hackintosh drain battery too fast.

Actually my battery backup is similar to when i was running windows. It doesn't drain too fast so its good

**Comment by pavankumar-go** [comment]
@kadalcj  which wifi adapter are you using? can i use it on my laptop?

**Comment by tareqmahmud** [comment]
> @kadalcj which wifi adapter are you using? can i use it on my laptop?

You can try this,

https://www.tp-link.com/en/support/download/tl-wn725n/

I'm using this right now, and it has an official driver for mac. But make sure the version is v3; otherwise, Catalina or big sur won't support.

**Comment by pavankumar-go** [comment]
> > @kadalcj which wifi adapter are you using? can i use it on my laptop?
> 
> You can try this,
> 
> https://www.tp-link.com/en/support/download/tl-wn725n/
> 
> I'm using this right now, and it has an official driver for mac. But make sure the version is v3; otherwise, Catalina or big sur won't support.

**Comment by pavankumar-go** [comment]
> > > @kadalcj which wifi adapter are you using? can i use it on my laptop?
> > 
> > 
> > You can try this,
> > https://www.tp-link.com/en/support/download/tl-wn725n/
> > I'm using this right now, and it has an official driver for mac. But make sure the version is v3; otherwise, Catalina or big sur won't support.

@tareqmahmud Thank you bro

**Comment by kadalcj** [comment]
> @kadalcj  which wifi adapter are you using? can i use it on my laptop? 
> 

I am using TP-WN821N. I recommend you try searching for another model because the one that I use was so sticking out from Laptop

**Comment by pavankumar-go** [comment]
okay thanks @kadalcj i just ordered one that @tareqmahmud  said

**Comment by pavankumar-go** [comment]
@kadalcj @tareqmahmud  sorry had one more question, are there any hacks for backlit keyboard?

**Comment by tareqmahmud** [comment]
> @kadalcj @tareqmahmud sorry had one more question, are there any hacks for backlit keyboard?

I failed to use the backlight keyboard and proper sleep mode on clover, and for that, I moved to OpenCore, and there almost everything works perfectly except wifi and Bluetooth.

**Comment by tareqmahmud** [comment]
If you want to use OpenCore instead of clover, then you can use my EFI, where most of the functionality done by the DSDT patch.

https://github.com/tareqmahmud/Asus-Vivobook-S430-FA-MacOS

**Comment by pavankumar-go** [comment]
> If you want to use OpenCore instead of clover, then you can use my EFI, where most of the functionality done by the DSDT patch.
> 
> https://github.com/tareqmahmud/Asus-Vivobook-S430-FA-MacOS

Thanks a lot man!, its working!!
