### ISSUE TITLE
The HDMI output is not working

### ISSUE THREAD

**Issue by RobinChiu** [kadalcj/Hackintosh_Catalina_Asus_VivoBook_S14_S430FN#2]
I tested the HDMI output, but it's not working. I try to use the hackintool to watch the connectors status when plug in the HDMI cable. But it didn't appear in it. Did you try it?

**Comment by kadalcj** [comment]
No, I haven't. I don't have any access to external display so I haven't try it.
Maybe you need to try different frame buffer to make the HDMI work
